import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Footer from "../components/Footer";
import AboutUs from "../components/AboutUs";
import Contact from "../components/Contact";
import Fetures from "../components/Fetures";
import faq from "../components/Faq";
import FAQ from "../components/FAQ";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Navigation using nextjs and tailwindcss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar />
      <Hero />
      <AboutUs />
      <Fetures />
      <FAQ />
      <Contact />
      <Footer />
    </div>
  );
}
